# Question 1 Gradient Discent

In [39]:
import numpy as np
import math
import pylab as pl
import random

%matplotlib inline

In [40]:
def negativeGaussian(x,mu,Sigma):
    detSigma = np.linalg.det(Sigma)
    n = len(x)
    NC = -((1/(np.sqrt(2*math.pi)**2)*detSigma)) # normalizing constant
    normalizedX = [a - b for a, b in zip(x, mu)] 
    invSigma = np.linalg.inv(Sigma)
    kernel = np.exp(-0.5*(np.inner(np.inner(normalizedX,invSigma),np.transpose(normalizedX))))
    
    value = -NC*kernel
    
    gradient = -value*np.inner(invSigma,normalizedX)
    
    return(value,gradient)
    

In [41]:
def qBowl(x,b,A):
    value = 0.5*np.inner(np.inner(np.transpose(x),A),x) - np.inner(np.transpose(x),b)
    gradient = np.inner(A,x) - b
    return (value,gradient)

In [42]:
a = [25,25]
mu = [1,3.2]
A = [[2,0.3],[0.4,3]]

In [54]:
def batchGradientDiscent(function,initGuess,step,threshold,maxIter,*args):
    gradientNorm = []
    epsilon = 1
    value = initGuess
    iteration = 0
    #while iteration > 1:
    #if iteration < maxIter:
    while epsilon > threshold and iteration < maxIter : 
       
        output = function(initGuess,*args)
        #print output
        
        gradient = output[1]
        newValue = value - step * gradient #GDS equation
        
        evaluateOld = function(value,*args)[0] # function evaluated at old point
        evaluateNew = function(newValue,*args)[0]# function evaluated at new point
        epsilon = abs(evaluateNew - evaluateOld)
        value = newValue
        gradient= function(value,*args)[1]
        gNorm = np.linalg.norm(gradient)
        gradientNorm .append(gNorm)
        #print epsilon
            

        iteration=iteration+1
        print(iteration)
          
        
        
    return(gradientNorm)

In [55]:
# Loading the parameters
def getData():

    # load the parameters for the negative Gaussian function and quadratic bowl function
    # return a tuple that contains parameters for Gaussian mean, Gaussian covariance,
    # A and b for quadratic bowl in order

    data = pl.loadtxt('../DataFiles/HW1/parametersp1.txt')

    gaussMean = data[0,:]
    gaussCov = data[1:3,:]

    quadBowlA = data[3:5,:]
    quadBowlb = data[5,:]

    return (gaussMean,gaussCov,quadBowlA,quadBowlb) 



In [56]:
gaussMean,gaussCov,quadBowlA,quadBowlb = getData()

In [57]:
qBowl(a,quadBowlb,quadBowlA)

(-10625.0, array([-25., -25.]))

In [58]:
quadBowlb

array([ 400.,  400.])

In [72]:
np.inner(np.linalg.inv(quadBowlA),quadBowlb)

array([ 26.66666667,  26.66666667])

In [62]:
batchGradientDiscent(negativeGaussian,[20,10],0.01,1e-2,10,gaussMean,gaussCov)

1
2
3
4
5
6
7
8
9
10


[2917.0210066242635,
 2848.4097399899583,
 1899.2427880139996,
 931.82567341155357,
 346.8006574783667,
 99.429589617843206,
 22.156966595003993,
 3.8592344609212286,
 0.52737973207221989,
 0.056692765775181071]

In [79]:
batchGradientDiscent(qBowl,[26.6,26.6],0.1,1e-2,1000,quadBowlb,quadBowlA)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


[0.70710678118654757,
 2.8284271247463511,
 4.9497474683059934,
 7.0710678118656363,
 9.192388155425359,
 11.313708498985001,
 13.435028842544645,
 15.556349186104287,
 17.67766952966393,
 19.798989873223654,
 21.920310216783296,
 24.041630560342938,
 26.16295090390274,
 28.284271247462382,
 30.405591591022027,
 32.526911934581669,
 34.648232278141315,
 36.769552621701116,
 38.890872965260755,
 41.0121933088204,
 43.133513652380124,
 45.254833995939762,
 47.376154339499408,
 49.497474683059053,
 51.618795026618692,
 53.740115370178415,
 55.861435713738061,
 57.982756057297699,
 60.104076400857501,
 62.225396744417147,
 64.346717087976799,
 66.46803743153643,
 68.589357775096076,
 70.710678118655878,
 72.831998462215523,
 74.953318805775169,
 77.074639149334885,
 79.195959492894531,
 81.317279836454176,
 83.438600180013808,
 85.559920523573453,
 87.681240867133184,
 89.802561210692815,
 91.923881554252461,
 94.045201897812277,
 96.166522241371908,
 98.287842584931553,
 100.4091629284912

Quadratic bowl shows some very erratic behavior unless the startiing point is very clos
and the threshold is relatively larger

## Question 2

In [ ]:
def finiteDifference(function,sp,h,*args):

    fdApprox = []
    for i in range(len(sp)):
        Lower = [float(j) for j in sp]
        Higher = [float(j) for j in sp]
        Lower[i] = Lower[i] - 0.5*h
        #print Lower
        Higher[i] = Higher[i] + 0.5*h
        print Lower
        print Higher
        higherValue = function(Higher,*args)[0]
        lowerValue = function(Lower,*args)[0]
        print higherValue
        print lowerValue
        fdApprox.append((higherValue - lowerValue)/h)
        #increment = [0.5*h + b for  b in sp]
        #higherInput = [a + b for a, b in zip(sp, increment)] 
        #lowerInput = [a - b for a, b in zip(sp, increment)]
        #higher = function( higherInput,*args)[0]
        #lower = function(lowerInput,*args)[0]
        #fdApprox = (higher - lower)/h
    return(fdApprox)


In [ ]:
finiteDifference(qBowl,[1,2],10000,quadBowlb,quadBowlA)

In [ ]:
qBowl([1,2],quadBowlb,quadBowlA)

In [ ]:
A = [32,23]
A[1] = A[1]+23
A
[float(i) for i in A]

In [ ]:
A = [2,3]
B = [23,4]
[0.5 + b for  b in A] 


In [90]:
# Loading the data

def getData():
    
    # load the fitting data for X and y and return as elements of a tuple
    # X is a 100 by 10 matrix and y is a vector of length 100
    # Each corresponding row for X and y represents a single data sample

    X = pl.loadtxt('../DataFiles/HW1/fittingdatap1_x.txt')
    y = pl.loadtxt('../DataFiles/HW1/fittingdatap1_y.txt')

    return (X,y) 

In [91]:
X,y = getData()

In [107]:
A = np.dot(np.linalg.inv(np.dot(np.transpose(X),X)),np.transpose(X))

In [108]:
sp = np.inner(A,y)

Least Square function

In [94]:
def leastSquare(theta,X,y):
    y = y.ravel()
    intermediate = np.inner(X,theta) - y
    value = np.inner(np.transpose(intermediate),intermediate)
    gradient = 2*np.inner(np.transpose(X),intermediate)
        
    return(value,gradient)


In [95]:
theta = [1,2,3,4,-5,6,7,8,9,-10]

In [96]:
y[5]

465.95999999999998

In [97]:
leastSquare(sp,X[5,],y[5])

ValueError: shapes (10,) and (1,) not aligned: 10 (dim 0) != 1 (dim 0)

In [ ]:
sp

In [ ]:
sp = [0.1]*10

In [ ]:
batchGradientDiscent(leastSquare,sp,0.1,0.001,36,X,y)

In [88]:
random.shuffle(theta)
theta

[-5, 1, 8, 6, 3, -10, 7, 4, 2, 9]

# Stochastic Gradient Discent

In [119]:
def stochasticGradientDiscent(X,Y,initGuess,threshold,maxIter,tau0,kappa):
    gradientNorm = []
    epsilon = 1
    value = initGuess
    iteration = 0

    n = X.shape[0]
    indTheta = initGuess
    k = kappa
    steps = 0
    random.shuffle(X)
    while epsilon > threshold :
        for j in range(maxIter):
            for i in range(n):
            
                indX = X[i,]
                indY = Y[i]
                value = (np.inner(np.transpose(indX),indTheta) - indY)**2
                gradient = 2*(np.inner(np.transpose(indX),indTheta) - indY)*indX
                #print(gradient)
                etaT = (1./(tau0+steps))**k
           
                #print output
            
                newTheta = indTheta - etaT*gradient
                epsilon = np.linalg.norm(gradient)
                #print(etaT)
                #print(newTheta)
                #print(indTheta)
            
                indTheta = newTheta
                print(indTheta)
                
        #return(indTheta)
            

        
          
        


In [120]:
i = 2
indTheta = sp
indX = X[i,]
indY = y[i]
value = (np.inner(np.transpose(indX),indTheta) - indY)**2
gradient = 2*(np.inner(np.transpose(indX),indTheta) - indY)*indX
print 2*(np.inner(np.transpose(indX),indTheta) - indY)*indX

[  -114.54643762    381.45831331 -17645.5207571   11490.20607272
   8398.38605957 -13494.92436474  -5899.68625533 -12865.23022535
  -5227.27065245   2141.67598917]


In [121]:
stochasticGradientDiscent(X,y,sp,0.001,3,2,0.7)

[  -64.51904405    76.43727663 -3581.16017214  2361.76575766  1670.90592055
 -2734.06964672 -1179.02697319 -2602.36947541 -1052.04487191   418.39105174]
[   43587.63922212  -145292.36694945  6720897.40773742 -4376406.39532149
 -3198844.84195775  5140006.17108811  2247114.70872654  4900169.62079076
  1990992.8460058   -815746.4865309 ]
[ -8.23100675e+07   2.74105807e+08  -1.26796023e+10   8.25655679e+09
   6.03485702e+09  -9.69709405e+09  -4.23935775e+09  -9.24461257e+09
  -3.75617778e+09   1.53895144e+09]
[  1.55285542e+11  -5.17126173e+11   2.39212525e+13  -1.55767645e+13
  -1.13853207e+13   1.82944724e+13   7.99794386e+12   1.74408239e+13
   7.08637975e+12  -2.90337547e+12]
[ -2.92960659e+14   9.75606761e+14  -4.51296741e+16   2.93870191e+16
   2.14794695e+16  -3.45142287e+16  -1.50888671e+16  -3.29037411e+16
  -1.33691164e+16   5.47748863e+15]
[  5.52697610e+17  -1.84057316e+18   8.51413397e+19  -5.54413526e+19
  -4.05230228e+19   6.51143117e+19   2.84665552e+19   6.20759768e+19
   

/Users/Divy/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:18: RuntimeWarning: overflow encountered in double_scalars
/Users/Divy/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:25: RuntimeWarning: invalid value encountered in subtract


In [ ]:
sp

In [ ]:
indX = X[i,]
indY = y[i]
value = (np.inner(np.transpose(indX),sp) - indY)**2
value
2*(np.inner(np.transpose(indX),sp) - indY)*indX

In [ ]:
def additional(function,f,d,*args):
    return(function(*args)+f**d)


In [ ]:
add(23,31)

In [ ]:
additional(mult,23,2,12,3)

In [ ]:
23**2

In [ ]:
abs(23-132)

In [ ]:
 x = np.arange(30).reshape(6,5)

In [ ]:
x[:,1]

In [ ]:
data = pl.loadtxt('../DataFiles/HW1/curvefittingp2.txt')

## Linear Basis Function Regression

In [ ]:
# Data for question 2
import matplotlib.pyplot as plt
import pylab as pl

def getData(ifPlotData=True):
    # load the fitting data and (optionally) plot out for examination
    # return the X and Y as a tuple

    data = pl.loadtxt('../DataFiles/HW1/curvefittingp2.txt')

    X = data[0,:]
    Y = data[1,:]

    if ifPlotData:
        plt.plot(X,Y,'o')
        plt.xlabel('x')
        plt.ylabel('y')
        plt.show()

    return (X,Y)

In [ ]:
X,Y = getData(ifPlotData=True)


In [228]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [229]:
def LBFRegression(X,y,m):
    designMat = np.zeros((len(X),m+1))
    for i in range(m+1):
        #print([a**i for a in X])
        designMat[:,i] = [a**i for a in X]
        
        
    mle = np.inner(np.dot(np.linalg.inv(np.dot(np.transpose(designMat),designMat)),np.transpose(designMat)),y)
    fittedValues = np.dot(designMat,np.transpose(mle))
    return(mle,fittedValues)

In [ ]:
fValue18 = LBFRegression(X,Y,18)[1]

In [ ]:
plt.plot(X,fValue18,'o')
plt.xlabel('x')
plt.ylabel('y')
plt.show()

In [ ]:
designMat = np.zeros((5,3))

In [ ]:
designMat[1,:] = A
designMat[2,:] = [a**2 for a in A] 
designMat[3,:] = [a**3 for a in A] 

In [ ]:
designMat


# Cosine basis function

In [ ]:
def CosBFRegression(X,y,m):
    designMat = np.zeros((len(X),m))
    for i in range(1,m+1):
        
        #print np.cos(i*np.pi*X)
        designMat[:,i-1] = np.cos(i*np.pi*X)
        
        
    mle = np.inner(np.dot(np.linalg.inv(np.dot(np.transpose(designMat),designMat)),np.transpose(designMat)),y)
    fittedValues = np.dot(designMat,np.transpose(mle))
    return(mle)

In [ ]:
CosBFRegression(X,Y,8)

In [ ]:
np.cos(4*np.pi*X)

# Ridge Regression 

In [11]:
# Data for question 3

import pdb
import random
import pylab as pl

# X is an array of N data points (one dimensional for now), that is, NX1
# Y is a Nx1 column vector of data values

def getData(name):
    data = pl.loadtxt(name)
    # Returns column matrices
    X = data[0:1].T
    Y = data[1:2].T
    return X, Y

def regressAData():
    return getData('../DataFiles/HW1/regressA_train.txt')

def regressBData():
    return getData('../DataFiles/HW1/regressB_train.txt')

def validateData():
    return getData('../DataFiles/HW1/regress_validate.txt')

In [12]:
regressAData()[0]

array([[ 1.29946363],
       [-0.80608991],
       [ 0.7569518 ],
       [-2.62790749],
       [-1.50589984],
       [-2.83632079],
       [-2.72378643],
       [ 1.13817614],
       [-1.23794415],
       [-1.40714309],
       [ 2.40714309],
       [ 2.30714309],
       [ 0.90714309]])

In [17]:
def ridgeRegression(X,y,lambdaShrink,m):
    designMat = np.zeros((len(X),m+1))
    for i in range(m+1):
        #print([a**i for a in X])
        designMat[:,i] = [a**i for a in X]
        designMat[:,i] = [j - np.mean(y) for j in designMat[:,i]] # Centering X's
        
    y = y.ravel() 
    
    yCentered = [j - np.mean(y) for j in y] # Centering y's
    
    mle = np.inner(np.dot(np.linalg.inv(np.dot(np.transpose(designMat),designMat)+lambdaShrink*np.identity(m+1)),np.transpose(designMat)),yCentered)
    fittedValues = np.dot(designMat,np.transpose(mle))
    return(mle,fittedValues)
    

Test 1

In [18]:
Train1_X = regressAData()[0]
Train1_Y = regressAData()[1]
Test1_X = regressBData()[0]
Test1_Y = regressBData()[1]
valid1_X =validateData()[0]
valid1_Y = validateData()[1]

In [19]:
ridgeParam

NameError: name 'ridgeParam' is not defined

In [33]:
def LBFRidgeRegression(theta,X,y,lambda_shrinkage):
    params = len(theta)
    #print (m)
    designMat = np.zeros((len(X),params))
    for i in range(params):
        #print([a**i for a in X])
        designMat[:,i] = [a**i for a in X]
        designMat[:,i] = [j - np.mean(y) for j in designMat[:,i]] # Centering X's
    
    y = y.ravel() 
    yCentered = [j - np.mean(y) for j in y]  # Centering y's
    
    
    fittedValues = np.dot(designMat,np.transpose(theta))
    fittedDifference = [a - b for a, b in zip(fittedValues,yCentered)]
    RSS = sum(a**2 for a in fittedDifference)+lambda_shrinkage*np.dot(theta,np.transpose(theta))
    return(fittedValues,RSS)

In [38]:
ridgeParam = ridgeRegression(Train1_X,Train1_Y,0.6,5)[0]
LBFRidgeRegression(ridgeParam,valid1_X ,valid1_Y,15)
#ridgeParam

(array([ 1.79407114,  0.90137955, -1.34963976, -1.92571202,  0.12248468,
        -0.23195515, -1.76788164, -1.48869352, -1.30998562, -1.3324572 ,
        -2.13197573, -0.69506116, -0.20151477, -2.93539211,  0.19682816,
        -1.46914259,  0.82750859,  1.10991989,  1.34064851, -2.08221341,
         1.48949314,  1.65475167]), 35.598423331853681)

Test 2

In [245]:
Train1_X = regressBData()[0]
Train1_Y = regressBData()[1]
Test1_X = regressAData()[0]
Test1_Y = regressAData()[1]

In [256]:
ridgeParam = ridgeRegression(Train1_X,Train1_Y,0.6,10)[0]

In [257]:
LBFRidgeRegression(ridgeParam,Test1_X ,Test1_Y)

(array([  2.14770993,   0.18476991,   1.72257668,   5.33057413,
         -2.19399598,  26.11913085,  12.81365765,   2.12672868,
         -0.92511617,  -1.66875885,  48.19063043,  29.48151876,   1.91391144]),
 248.96639489346109)

# Question 4 (Sparsity and LASSO)

In [3]:
# Data for this question
import pdb
import random
import pylab as pl

# X is an array of N data points (one dimensional for now), that is, NX1
# Y is a Nx1 column vector of data values

def getData(name):
    data = pl.loadtxt(name)
    # Returns column matrices
    X = data[0:1].T
    Y = data[1:2].T
    return X, Y

def lassoTrainData():
    return getData('../DataFiles/HW1/lasso_train.txt')

def lassoValData():
    return getData('../DataFiles/HW1/lasso_validate.txt')

def lassoTestData():
    return getData('../DataFiles/HW1/lasso_test.txt')


In [4]:
from sklearn import linear_model

clf = linear_model.Lasso(alpha=0.1,fit_intercept=False) # alpha is the shrinkage parameter
clf.fit([[0,0], [1, 1], [2, 2]], [0, 1, 2])
print(clf.coef_)
print(clf.intercept_)


[ 0.94  0.  ]
0.0


In [306]:

def sineBasisFunction(X,y,n=13):
    designMat = np.zeros((len(X),n))
    designMat[:,0] = X.ravel()
    for i in range(1,n):
        #print([a**i for a in X])
        designMat[:,i] = [np.sin(0.4*np.pi*a*i) for a in X]
    return(designMat,y)

In [5]:
X = lassoTrainData()[0]
y = lassoTrainData()[1]

In [309]:
designMat = sineBasisFunction(X,y,n=13)[0]
outcome = sineBasisFunction(X,y,n=13)[1]

In [310]:
clf.fit(designMat, outcome)

Lasso(alpha=0.1, copy_X=True, fit_intercept=False, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [311]:
print(clf.coef_)

[ 0.          0.          5.49526681  0.33802335  0.          1.12455954
  2.28295397  0.          0.         -0.         -0.          0.          0.        ]


In [320]:
def ridgeRegressionGeneral(X,y,lambdaShrink):
    designMat = X
    m = X.shape[1]
    y = y.ravel() 
    mle = np.inner(np.dot(np.linalg.inv(np.dot(np.transpose(designMat),designMat)+lambdaShrink*np.identity(m)),np.transpose(designMat)),y)
    fittedValues = np.dot(designMat,np.transpose(mle))
    return(mle,fittedValues)
    

In [323]:
ridgeRegressionGeneral(designMat,y,7)

(array([ 0.78892831,  0.8659637 ,  1.14612021,  0.86954421,  0.56026403,
         0.56512953,  0.68207974,  0.52355505,  0.09691978, -0.17692136,
        -0.03052377,  0.25532703,  0.17543088]),
 array([-3.69000726, -1.37665884,  2.7225307 ,  3.66210977, -2.49720775]))

In [318]:
X.shape[1]

1

In [3]:
A = [2,3,2,3]
a = 4
[b - a for b in A]

[-2, -1, -2, -1]

In [7]:
np.mean(A)

2.5