# Homework 0 

In [1]:
from numpy import matrix
import numpy as np
import itertools

In [2]:
A = matrix([[1,2,3],[11,12,13],[21,22,23]])

In [3]:
B = np.random.rand(30,30)

In [4]:
C =np.diag_indices_from(A)

In [5]:
A[C[0]]

matrix([[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23]])

In [6]:
C[0]

array([0, 1, 2])

In [7]:
v = np.diag(A)+12

In [8]:
v

array([13, 24, 35])

In [10]:
np.diag(np.diag(v))

array([13, 24, 35])

In [11]:
A

matrix([[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23]])

In [12]:
A[0,0] = 3

In [13]:
A

matrix([[ 3,  2,  3],
        [11, 12, 13],
        [21, 22, 23]])

In [15]:
C = np.fill_diagonal(A,[23,23,12])

Add 10 to each diagonal element of a matrix

In [16]:
np.fill_diagonal(B,np.diag(B)+10)

Find largest non-diagonal element

# Solutions

## Question 1

In [17]:
A = matrix([[1,2,3],[11,12,13],[21,22,23]])

In [18]:
A

matrix([[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23]])

In [19]:
A = A + np.eye(3)

In [20]:
A

matrix([[  2.,   2.,   3.],
        [ 11.,  13.,  13.],
        [ 21.,  22.,  24.]])

In [21]:
idx = np.ravel_multi_index((range(3), range(3)), A.shape)
A.flat[idx] += 1

In [22]:
# np.ravel_multi_index Converts a tuple of index arrays into an array of flat indices, 
# applying boundary modes to the multi-index.

In [23]:
# flat array over an iterator

In [24]:
A

matrix([[  3.,   2.,   3.],
        [ 11.,  14.,  13.],
        [ 21.,  22.,  25.]])

In [25]:
idx

array([0, 4, 8])

In [26]:
range(3)

[0, 1, 2]

In [27]:
A.shape

(3, 3)

In [28]:
np.ravel_multi_index((range(2), range(2)), A.shape)

array([0, 4])

In [29]:
(range(3), range(3))

([0, 1, 2], [0, 1, 2])

## Question 2

In [30]:
A

matrix([[  3.,   2.,   3.],
        [ 11.,  14.,  13.],
        [ 21.,  22.,  25.]])

In [31]:
A - A.flat[idx]

matrix([[  0., -12., -22.],
        [  8.,   0., -12.],
        [ 18.,   8.,   0.]])

In [32]:
A.flat[idx]

matrix([[  3.,  14.,  25.]])

In [35]:
msk = (np.eye(3) == 0)

In [36]:
msk

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]], dtype=bool)

In [37]:
v = np.max(A[msk])

In [38]:
n = 3

Finding the maximum of the matrix and the location of the maximum

In [39]:
I = np.tile(np.array(range(n)).T, (n, 1)).transpose() # tile for repeating a list or an array


In [40]:
J = I.transpose()
idx = np.argwhere(I != J)
idx_r = [np.ravel_multi_index(x, A.shape) for x in idx]
idx_r
v = np.max(A.flat[idx_r]) # the maximum off-diagonal element
max_loc = np.argmax(A.flat[idx_r])
i, j = np.unravel_index(max_loc, A.shape)
i,j

(1, 2)

## Question 3

In [41]:
# generate an array to use np.newaxis
x = np.array([23,32,43,12,323,4,5,6,64])
y = np.array([22,23,56,57,5674,456,45,46,123])

In [42]:
# Using for loop

F= np.empty((len(x),len(y)))
J = np.empty((len(x),len(y)))
for i in range(len(x)):
    for j in range(len(y)):
        F[i,j] = x[i]+y[j]
        J[i,j] = x[i]*y[j]

In [43]:
# Without using for loop
A = x[:, np.newaxis] + y[np.newaxis, :]
B = x[:, np.newaxis] * y[np.newaxis, :]

In [44]:
np.zeros((3,5))[:,np.newaxis,:]

array([[[ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.]]])

In [45]:
np.zeros((3,5))[:,np.newaxis,]

array([[[ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.]]])

In [46]:
x

array([ 23,  32,  43,  12, 323,   4,   5,   6,  64])