# Homework 0 

In [103]:
from numpy import matrix
import numpy as np
import itertools

In [3]:
A = matrix([[1,2,3],[11,12,13],[21,22,23]])

In [45]:
B = np.random.rand(30,30)

In [14]:
C =np.diag_indices_from(A)

In [18]:
A[C[0]]

matrix([[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23]])

In [19]:
C[0]

array([0, 1, 2])

In [22]:
v = np.diag(A)+12

In [23]:
v

array([13, 24, 35])

In [24]:
np.diag(A) = v

SyntaxError: can't assign to function call (<ipython-input-24-24feebef1974>, line 1)

In [27]:
np.diag(np.diag(v))

array([13, 24, 35])

In [26]:
A

matrix([[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23]])

In [30]:
A[0,0] = 3

In [31]:
A

matrix([[ 3,  2,  3],
        [11, 12, 13],
        [21, 22, 23]])

In [32]:
np.fill_diagonal(A)=[23,23,12]

SyntaxError: can't assign to function call (<ipython-input-32-731eca08a577>, line 1)

In [36]:
C = np.fill_diagonal(A,[23,23,12])

Add 10 to each diagonal element of a matrix

In [46]:
np.fill_diagonal(B,np.diag(B)+10)

In [47]:
B

array([[  1.05003905e+01,   2.69513273e-01,   4.10006027e-01,
          5.13491788e-01,   5.31210037e-01,   5.84407461e-01,
          1.88498706e-01,   1.54958872e-01,   9.99273849e-01,
          1.37268256e-02,   9.60309985e-02,   1.77992652e-01,
          5.03873426e-02,   9.21923880e-01,   6.68972598e-02,
          3.31372667e-01,   1.26140361e-01,   8.35085530e-01,
          2.28558040e-01,   6.28330924e-01,   2.07910161e-01,
          2.38158773e-02,   3.48434661e-01,   7.65697941e-01,
          4.09321636e-01,   9.03043478e-01,   3.51773742e-01,
          3.85124200e-01,   8.81361086e-01,   9.22508374e-01],
       [  3.68493836e-01,   1.04727970e+01,   6.72993584e-02,
          1.59262559e-01,   5.13369938e-01,   6.94077837e-01,
          7.27261996e-01,   1.28573679e-01,   3.13233933e-01,
          1.30184149e-01,   6.50602799e-01,   5.59915560e-01,
          5.47238871e-01,   7.65749712e-01,   1.20749110e-02,
          4.16131198e-02,   9.64863529e-01,   4.42266370e-02,
       

Find largest non-diagonal element

# Solutions

## Question 1

In [3]:
A = matrix([[1,2,3],[11,12,13],[21,22,23]])

In [4]:
A

matrix([[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23]])

In [5]:
A = A + np.eye(3)

In [6]:
A

matrix([[  2.,   2.,   3.],
        [ 11.,  13.,  13.],
        [ 21.,  22.,  24.]])

In [9]:
idx = np.ravel_multi_index((range(3), range(3)), A.shape)
A.flat[idx] += 1

In [ ]:
# np.ravel_multi_index Converts a tuple of index arrays into an array of flat indices, 
# applying boundary modes to the multi-index.

In [14]:
# flat array over an iterator

In [10]:
A

matrix([[  3.,   2.,   3.],
        [ 11.,  14.,  13.],
        [ 21.,  22.,  25.]])

In [11]:
idx

array([0, 4, 8])

In [12]:
range(3)

[0, 1, 2]

In [13]:
A.shape

(3, 3)

In [15]:
np.ravel_multi_index((range(2), range(2)), A.shape)

array([0, 4])

In [18]:
(range(3), range(3))

([0, 1, 2], [0, 1, 2])

## Question 2

In [39]:
A

matrix([[  3.,   2.,   3.],
        [ 11.,  14.,  13.],
        [ 21.,  22.,  25.]])

In [38]:
A - A.flat[idx]

matrix([[  0., -12., -22.],
        [  8.,   0., -12.],
        [ 18.,   8.,   0.]])

In [24]:
A.flat[idx]

matrix([[  3.,  14.,  25.]])

array([0, 4, 8])

In [29]:
a

[2, 3, 4, 23, 3, 1241, 1]

[3, 1241, 1]

In [42]:
msk = (np.eye(3) == 0)

In [43]:
msk

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]], dtype=bool)

In [44]:
v = np.max(A[msk])

In [50]:
n = 3

Finding the maximum of the matrix and the location of the maximum

In [53]:
I = np.tile(np.array(range(n)).T, (n, 1)).transpose() # tile for repeating a list or an array


array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [84]:
J = I.transpose()
idx = np.argwhere(I != J)
idx_r = [np.ravel_multi_index(x, A.shape) for x in idx]
idx_r
v = np.max(A.flat[idx_r]) # the maximum off-diagonal element
max_loc = np.argmax(A.flat[idx_r])
i, j = np.unravel_index(max_loc, A.shape)
i,j

(1, 2)

## Question 3

In [138]:
# generate an array to use np.newaxis
x = np.array([23,32,43,12,323,4,5,6,64])
y = np.array([22,23,56,57,5674,456,45,46,123])

In [136]:
# Using for loop

F= np.empty((len(x),len(y)))
J = np.empty((len(x),len(y)))
for i in range(len(x)):
    for j in range(len(y)):
        F[i,j] = x[i]+y[j]
        J[i,j] = x[i]*y[j]

In [137]:
# Without using for loop
A = x[:, np.newaxis] + y[np.newaxis, :]
B = x[:, np.newaxis] * y[np.newaxis, :]

In [121]:
np.zeros((3,5))[:,np.newaxis,:]

array([[[ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.]]])

In [124]:
np.zeros((3,5))[:,np.newaxis,]

array([[[ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.]]])

In [127]:
x

array([ 23,  32,  43,  12, 323,   4,   5,   6,  64])